font-family = JetBrains Mono
font-family-bold = JetBrains Mono
font-family-italic = JetBrains Mono
font-family-bold-italic = JetBrains Mono
font-style = Medium
font-style-bold = Bold
font-style-italic = Medium Italic
font-style-bold-italic = Bold Italic
adjust-cell-height = 0%
window-height = 38
window-width = 135
theme = dark:"Catppuccin Frappe",light:"Catppuccin Latte"
custom-shader = /Users/mac/dev/dotfiles/files_to_symlink/ghostty/shaders/cursor_warp.glsl
