#!/usr/bin/env bash

set -euo pipefail

state_root="${TMUX_BACKGROUND_STATE_ROOT:-${XDG_STATE_HOME:-$HOME/.local/state}/tmux-ui}"
state_file="$state_root/moving-background"
ghostty_config_dir="${TMUX_BACKGROUND_GHOSTTY_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/ghostty}"
ghostty_override="$ghostty_config_dir/background.ghostty"
active_shader="$ghostty_config_dir/shaders/moving_stars-active.glsl"
no_reload="${TMUX_BACKGROUND_NO_RELOAD:-0}"

resolve_source_root() {
    local script_path="${BASH_SOURCE[0]}"
    local script_dir
    local link_target

    if [[ -n ${TMUX_BACKGROUND_SOURCE_ROOT:-} ]]; then
        printf '%s' "$TMUX_BACKGROUND_SOURCE_ROOT"
        return 0
    fi

    while [[ -L $script_path ]]; do
        script_dir="$(cd -P "$(dirname "$script_path")" && pwd)"
        link_target="$(readlink "$script_path")"
        if [[ $link_target == /* ]]; then
            script_path="$link_target"
        else
            script_path="$script_dir/$link_target"
        fi
    done

    cd -P "$(dirname "$script_path")" && pwd
}

source_root="$(resolve_source_root)"
shader_template="$source_root/ghostty/shaders/moving_stars.glsl"

enabled="on"
speed="medium"
density="normal"
brightness="normal"

load_state() {
    local key
    local value

    enabled="on"
    speed="medium"
    density="normal"
    brightness="normal"

    if [[ -f $state_file ]]; then
        while IFS='=' read -r key value; do
            case "$key" in
                enabled) enabled="$value" ;;
                speed) speed="$value" ;;
                density) density="$value" ;;
                brightness) brightness="$value" ;;
            esac
        done < "$state_file"
    fi

    case "$enabled" in on | off) ;; *) enabled="on" ;; esac
    case "$speed" in slow | medium | fast) ;; *) speed="medium" ;; esac
    case "$density" in sparse | normal | dense) ;; *) density="normal" ;; esac
    case "$brightness" in subtle | normal | bright) ;; *) brightness="normal" ;; esac
}

save_state() {
    local temporary_file

    mkdir -p "$state_root"
    temporary_file="$(mktemp "$state_root/moving-background.XXXXXX")"
    printf 'enabled=%s\nspeed=%s\ndensity=%s\nbrightness=%s\n' \
        "$enabled" "$speed" "$density" "$brightness" > "$temporary_file"
    mv "$temporary_file" "$state_file"
}

render_shader() {
    local speed_multiplier
    local density_start
    local density_end
    local brightness_multiplier
    local temporary_file

    case "$speed" in
        slow) speed_multiplier="0.45" ;;
        medium) speed_multiplier="1.00" ;;
        fast) speed_multiplier="1.80" ;;
    esac

    case "$density" in
        sparse)
            density_start="0.965"
            density_end="0.990"
            ;;
        normal)
            density_start="0.930"
            density_end="0.975"
            ;;
        dense)
            density_start="0.880"
            density_end="0.950"
            ;;
    esac

    case "$brightness" in
        subtle) brightness_multiplier="0.18" ;;
        normal) brightness_multiplier="0.30" ;;
        bright) brightness_multiplier="0.48" ;;
    esac

    if [[ ! -f $shader_template ]]; then
        printf 'Missing moving-star shader template: %s\n' "$shader_template" >&2
        return 1
    fi

    mkdir -p "$ghostty_config_dir/shaders"
    temporary_file="$(mktemp "$ghostty_config_dir/shaders/moving_stars-active.XXXXXX")"
    sed -E \
        -e "s/^const float STAR_SPEED_MULTIPLIER = [^;]+;/const float STAR_SPEED_MULTIPLIER = $speed_multiplier;/" \
        -e "s/^const float STAR_DENSITY_START = [^;]+;/const float STAR_DENSITY_START = $density_start;/" \
        -e "s/^const float STAR_DENSITY_END = [^;]+;/const float STAR_DENSITY_END = $density_end;/" \
        -e "s/^const float STAR_BRIGHTNESS = [^;]+;/const float STAR_BRIGHTNESS = $brightness_multiplier;/" \
        "$shader_template" > "$temporary_file"
    chmod 0644 "$temporary_file"
    mv "$temporary_file" "$active_shader"
}

write_ghostty_override() {
    local dark_theme="Catppuccin Macchiato"
    local temporary_file

    if [[ $enabled == "on" ]]; then
        dark_theme="Catppuccin Macchiato Stars"
    fi

    mkdir -p "$ghostty_config_dir"
    temporary_file="$(mktemp "$ghostty_config_dir/background.ghostty.XXXXXX")"
    printf '# Generated by tmux-background.sh; edit through the tmux popup.\n' > "$temporary_file"
    printf 'theme = dark:%s,light:Catppuccin Latte\n' "$dark_theme" >> "$temporary_file"
    mv "$temporary_file" "$ghostty_override"
}

refresh_tmux_clients() {
    local client_tty

    [[ $no_reload == "1" ]] && return 0
    command -v tmux >/dev/null 2>&1 || return 0
    while IFS= read -r client_tty; do
        if [[ -n $client_tty ]]; then
            tmux refresh-client -S -t "$client_tty" 2>/dev/null || true
        fi
    done < <(tmux list-clients -F '#{client_tty}' 2>/dev/null || true)
}

reload_ghostty() {
    local hs_bin

    [[ $no_reload == "1" ]] && return 0
    hs_bin="$(command -v hs 2>/dev/null || true)"
    if [[ -n $hs_bin ]]; then
        "$hs_bin" -c \
            'local app=hs.application.get("com.mitchellh.ghostty"); return not app or app:selectMenuItem("Reload Configuration")' \
            >/dev/null 2>&1 || true
    fi
}

apply_settings() {
    save_state
    render_shader
    write_ghostty_override
    reload_ghostty
    refresh_tmux_clients
}

set_setting() {
    local setting="$1"
    local value="$2"

    case "$setting" in
        enabled)
            case "$value" in on | off) enabled="$value" ;; *) return 2 ;; esac
            ;;
        speed)
            case "$value" in slow | medium | fast) speed="$value" ;; *) return 2 ;; esac
            ;;
        density)
            case "$value" in sparse | normal | dense) density="$value" ;; *) return 2 ;; esac
            ;;
        brightness)
            case "$value" in subtle | normal | bright) brightness="$value" ;; *) return 2 ;; esac
            ;;
        *) return 2 ;;
    esac
}

cycle_setting() {
    case "$1" in
        enabled)
            [[ $enabled == "on" ]] && enabled="off" || enabled="on"
            ;;
        speed)
            case "$speed" in slow) speed="medium" ;; medium) speed="fast" ;; fast) speed="slow" ;; esac
            ;;
        density)
            case "$density" in sparse) density="normal" ;; normal) density="dense" ;; dense) density="sparse" ;; esac
            ;;
        brightness)
            case "$brightness" in subtle) brightness="normal" ;; normal) brightness="bright" ;; bright) brightness="subtle" ;; esac
            ;;
        *) return 2 ;;
    esac
}

display_value() {
    case "$1" in
        on) printf 'On' ;;
        off) printf 'Off' ;;
        slow) printf 'Slow' ;;
        medium) printf 'Medium' ;;
        fast) printf 'Fast' ;;
        sparse) printf 'Sparse' ;;
        normal) printf 'Normal' ;;
        dense) printf 'Dense' ;;
        subtle) printf 'Subtle' ;;
        bright) printf 'Bright' ;;
    esac
}

picker_rows() {
    local animation_icon="○"

    [[ $enabled == "on" ]] && animation_icon="●"
    printf '%s  %-13s %-8s\tenabled\n' "$animation_icon" "Animation" "$(display_value "$enabled")"
    printf '↔  %-13s %-8s\tspeed\n' "Speed" "$(display_value "$speed")"
    printf '✦  %-13s %-8s\tdensity\n' "Density" "$(display_value "$density")"
    printf '◐  %-13s %-8s\tbrightness\n' "Brightness" "$(display_value "$brightness")"
}

picker() {
    local action
    local position=1
    local rows
    local selection

    load_state
    while true; do
        rows="$(picker_rows)"
        selection="$(
            fzf \
                --delimiter=$'\t' \
                --with-nth=1 \
                --layout=reverse \
                --border=none \
                --no-multi \
                --sync \
                --prompt='Background › ' \
                --header='Enter or click cycles · Esc close' \
                --bind="start:pos($position)" \
                --bind='left-click:accept' \
                <<< "$rows"
        )" || return 0

        action="$(printf '%s' "$selection" | cut -f2)"
        case "$action" in
            enabled) position=1 ;;
            speed) position=2 ;;
            density) position=3 ;;
            brightness) position=4 ;;
            *) continue ;;
        esac
        cycle_setting "$action"
        apply_settings
    done
}

show_state() {
    printf 'enabled=%s\nspeed=%s\ndensity=%s\nbrightness=%s\n' \
        "$enabled" "$speed" "$density" "$brightness"
}

case "${1:-}" in
    ensure)
        load_state
        save_state
        render_shader
        write_ghostty_override
        ;;
    apply)
        load_state
        apply_settings
        ;;
    toggle)
        load_state
        cycle_setting enabled
        apply_settings
        ;;
    set)
        load_state
        if ! set_setting "${2:-}" "${3:-}"; then
            printf 'Unsupported moving-background setting: %s=%s\n' "${2:-}" "${3:-}" >&2
            exit 2
        fi
        apply_settings
        ;;
    show)
        load_state
        show_state
        ;;
    picker)
        picker
        ;;
    picker-rows)
        load_state
        picker_rows
        ;;
    *)
        printf 'Usage: %s {ensure|apply|toggle|set SETTING VALUE|show|picker|picker-rows}\n' "$0" >&2
        exit 2
        ;;
esac
